name: CI

on:
  push:
    paths:
      - 'Dockerfile'
      - 'main.py'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Bump version and push tag
        id: tag_release
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Cleanup Version for Docker Tag
        id: docker_tag
        run: |
          tag="${{ steps.tag_release.outputs.tag }}"
          version="${tag#v}"
          echo "version=$version" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/myrck/easyepg-lite:latest
            docker.io/myrck/easyepg-lite:${{ steps.docker_tag.outputs.version }}
            ghcr.io/myrck/easyepg-lite:latest
            ghcr.io/myrck/easyepg-lite:${{ steps.docker_tag.outputs.version }}
